apiVersion: v1
items:
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    labels:
      app.kubernetes.io/name: nc
      app.kubernetes.io/version: "1.0"
    name: nc
    namespace: default
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/name: nc
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/name: nc
      spec:
        containers:
        - command:
          - bash
          - -c
          - |
            mkdir -p /tmp/tcpdump && apt update && apt install curl netcat-openbsd -y 
            curl -LO https://raw.githubusercontent.com/mutazn/Cyclic_trace_linux/main/abc.sh
            chmod +x abc.sh
            sh abc.sh
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          image: ubuntu:18.04
          imagePullPolicy: IfNotPresent
          name: nc
          resources:
            limits:
              cpu: 100m
              memory: 90Mi
            requests:
              cpu: 100m
              memory: 90Mi
          securityContext:
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp/tcpdump
            name: tcpdump
        dnsPolicy: ClusterFirst
        hostNetwork: true
        hostPID: true
        nodeSelector:
          kubernetes.io/os: linux
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: tcpdump
          persistentVolumeClaim:
            claimName: tcpdump
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate
  status:
    currentNumberScheduled: 2
    desiredNumberScheduled: 2
    numberAvailable: 2
    numberMisscheduled: 0
    numberReady: 2
    observedGeneration: 23
    updatedNumberScheduled: 2
kind: List
metadata:
  resourceVersion: ""
