apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: tcpdump
    app.kubernetes.io/name: tcpdump
  name: tcpdump
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: azurefile
  volumeMode: Filesystem
