#In case you need to use static Azure file then you have to create a kubernetes secret:
#STORAGE_KEY=$(az storage account keys list --resource-group <storage-account-rg> --account-name <storage-account-name> --query "[0].value" -o tsv)
#AKS_PERS_STORAGE_ACCOUNT_NAME=<storage-account-rg>
#kubectl create secret generic azure-secret --from-literal=azurestorageaccountname=$AKS_PERS_STORAGE_ACCOUNT_NAME --from-literal=azurestorageaccountkey=$STORAGE_KEY
#create share file name called tcpdump-files
#Add (volumeName: azurefile) under spec to the pvc yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: azurefile
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: azurefile-tcpdumpfiles  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      #resourceGroup: resourceGroupName  # optional, only set this when storage account is not in the same resource group as node
      shareName: tcpdump-files
    nodeStageSecretRef:
      name: azure-secret
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
